name: bae_dualarm_doll_in_box_LRcam_relative

image_shape: [3, 240, 320]
dataset_path: data/baetae/251103/diffusion_doll_in_box_251103.hdf5

# relative 
low_dim_obs_horizon: 2
img_obs_horizon: 2
action_horizon: 16
ignore_proprioception: False


shape_meta: &shape_meta
  obs:
    image0:   # Left camera
      shape: [3, 240, 320]
      type: rgb
      horizon: ${task.img_obs_horizon}
      
    image1:   # Right camera
      shape: [3, 240, 320]
      type: rgb
      horizon: ${task.img_obs_horizon}

    robot_pose_L:
      shape: [3]
      type: low_dim
      horizon: ${task.low_dim_obs_horizon}
      
    robot_quat_L:
      shape: [4]
      type: low_dim
      horizon: ${task.low_dim_obs_horizon}
      rotation_rep: rotation_6d
      
    robot_pose_R:
      shape: [3]
      type: low_dim
      horizon: ${task.low_dim_obs_horizon}
      
    robot_quat_R:
      shape: [4]
      type: low_dim
      horizon: ${task.low_dim_obs_horizon}
      rotation_rep: rotation_6d
      
    hand_pose_L:
      shape: [7]
      type: low_dim
      horizon: ${task.low_dim_obs_horizon}
      
    hand_pose_R:
      shape: [7]
      type: low_dim
      horizon: ${task.low_dim_obs_horizon}
    
  action: 
    shape: [32] # robot_pose_L[3] + robot_rot6d_L[6] + robot_pose_R[3] + robot_rot6d_R[6] + hand_pose_L[7] + hand_pose_R[7]
    horizon: ${task.action_horizon}
    rotation_rep: rotation_6d


pose_repr: &pose_repr
  obs_pose_repr: abs # abs or relative
  action_pose_repr: abs # abs or relative or delta
  
  
env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.bae_robomimic_replay_image_dataset.BaeRobomimicReplayDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  # pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  # n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  # max_train_episodes: null
  # delta_action: False
  pose_repr: *pose_repr
  # abs_action: True
